pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "GIRO Platform Angola"
include ':giro_core'
include ':giro_passenger_app'
include ':giro_driver_app'
include ':giro_central_24h'
include ':giro_admin_vault'
